### ISSUE TITLE
Same Output for Different Time Steps and Parameters in VisMap Plots

### ISSUE THREAD

**Issue by PVR93** [FireDynamics/fdsvismap#15]
Hello,

I'm working on a fire safety project using the fdsvismap tool to visualize visibility based on FDS simulations. Using the example that is provided I am facing an issue where the ASET maps and the Time and Waypoint Aggregated Visibility Maps look the same across different time steps (t) and constant values (c), even though I expect visibility to decrease with increasing time due to smoke accumulation.

Here’s the key part of my code:

```
from fdsvismap import VisMap
from pathlib import Path
import matplotlib.pyplot as plt

project_root = Path(__file__).parent
bg_img = project_root / "misc" / "floorplan.png"
sim_dir = str(project_root / "fds_data")

time_steps = [60, 180, 300]
c_values = [3, 8]

for c in c_values:
    for t in time_steps:
        vis = VisMap()
        vis.quantity = 'SOOT EXTINCTION COEFFICIENT'
        vis.read_fds_data(sim_dir)
        vis.add_background_image(bg_img)
        
        min_vis = 5.0
        max_vis = 30.0
        vis.set_visibility_bounds(min_vis, max_vis)
        
        vis.set_start_point(1, 9)
        vis.set_waypoint(1, 8.4, 4.8, c, 0)
        vis.set_waypoint(2, 9.8, 4, c, 270)
        vis.set_waypoint(3, 17, 10, c, 180)
        
        times = range(0, t + 1, 20)
        vis.set_time_points(times)

        vis.add_visual_obstruction(15, 15.2, 0, 4)
        vis.add_visual_obstruction(16, 20, 4, 4.2)

        vis.compute_all()

        fig, ax = vis.create_aset_map_plot(max_time=t, plot_obstructions=True, flip_y_axis=False)
        ax.set_xlim(0, 20)
        ax.set_ylim(0, 10)
        ax.set_title(f'ASET Map, c={c}, t={t} sec, vis={min_vis}-{max_vis} m', fontsize=12)
        plt.savefig(f'aset_map_c_{c}_t_{t}_vis_{min_vis}-{max_vis}.pdf', dpi=600)
        plt.close()

        fig, ax = vis.create_time_agg_wp_agg_vismap_plot()
        ax.set_xlim(0, 20)
        ax.set_ylim(0, 10)
        ax.set_title(f'Time Aggregated Visibility Map, c={c}, t={t} sec, vis={min_vis}-{max_vis} m', fontsize=12)
        plt.savefig(f'time_agg_wp_agg_vismap_c_{c}_t_{t}_vis_{min_vis}-{max_vis}.pdf', dpi=600)
        plt.close()
```

Despite varying t and c, the resulting plots are visually identical, with only the titles and filenames reflecting the different values. I expect the visibility to decrease over time as more smoke accumulates, but this doesn't seem to happen in my visualizations.

I suspect it could be an issue with how the data is read or processed in the VisMap class, but I’m not sure where the problem lies. Could you please advise on what might be causing this behavior and how I can ensure the visibility maps reflect the changes in time and c?

**Comment by kriboe90** [comment]
I will have a look at it and see if I can reproduce the error. Data reading may be an issue. Can you please provide me with the FDSReader that is installed in your Python environment?

Thanks

**Comment by PVR93** [comment]
Hello,

Thank you for looking into this. Here's the information about the FDSReader installed in my Python environment:

Name: fdsreader
Version: 1.10.4
Summary: Python reader for data generated by FDS.
Home-page: https://github.com/FireDynamics/fdsreader
Author: FZJ IAS-7 (Jan Vogelsang, Prof. Dr. Lukas Arnold, Tristan Hehnen)
Author-email: ***@***.******@***.***>
License:
Location: C:\Users\pev\AppData\Local\Programs\Python\Python312\Lib\site-packages
Requires: incremental, numpy, typing-extensions
Required-by: fdsvismap

If you need any additional information, feel free to let me know.

Thanks again for your support!

Regards,

Pedro Vargas

**Comment by kriboe90** [comment]
I'm using the same version of FDSReader, and in my case, the data import didn't appear to cause any issues. How long did you run the FDS simulation? With the code provided, I also didn’t notice any differences at the initial time steps. However, when I extended the simulation to 600 s, I observed a visible effect, as shown in the attached image (ASET map). It seems that at earlier time steps, the smoke just doesn't have a significant impact on visibility.

Please let me know if that solves your issue.

Best

Kristian
[aset_map_c_3_t_600_vis_5.0-30.0.pdf](https://github.com/user-attachments/files/17340534/aset_map_c_3_t_600_vis_5.0-30.0.pdf)

**Comment by PVR93** [comment]
Hi Kristian,

Thank you for the response and the file you sent. I tried extending my simulation to 600 seconds and ran it at different time steps, but unfortunately, I’m still not seeing the differences you mentioned. My output is not matching with what you observed.

Did you make any modifications to the code, or do you think it could be worth reinstalling the FDSReader? It seems like something isn’t working properly on my end.

I’ve attached the files I obtained for comparison. I would appreciate any further guidance you can offer.

Thanks again for your help!

Best regards,

Pedro Vargas Rolon

**Comment by kriboe90** [comment]
Hi Pedro,

I did not make any other modifications to the code. Did you run the FDS simulation till the respective time step? Inside your loop, you can test the available FDS time points and the time points you set via:
print(vis.fds_time_points)
print(vis.vismap_time_points)

Reinstalling the FDSReader might be an idea, but I am not sure that solves the issue.

Best

Kristian

**Comment by PVR93** [comment]
Hi Kristian,

Thanks for the clarification. I ran my simulation again just to make sure no changes were made, but I’m still seeing the same results.

I also noticed that in your PDF, the map shows values across the full color spectrum, while my plots are only showing either the red or blue extremes (the limits). Do you think this could be due to my simulation files, or might I need to install something additional, like another Python class or dependency?

I’ve attached my latest map for comparison to give you an idea of the differences between your map and my results.

Thanks again for your continued support!

Pedro Vargas

**Comment by PVR93** [comment]
Hi Kristian,

I wanted to follow up on the previous discussion regarding the ASET map issue. In addition to the points I mentioned earlier, I’ve started receiving the following warning message when running the code in a different interface:

```
WARNING:root:Module vents: could not convert string to float: '!'
The error can be safely ignored if not requiring the vents module. However, please consider to submit an issue on Github including the error message, the stack trace and your FDS input-file so we can reproduce the error and fix it as soon as possible!
```

Do you think this could be related to why I’m not seeing the expected results in my plots? Could this warning indicate an issue with the data being used in my visibility calculations?

Thanks again for your continued support! I look forward to your insights.

**Comment by kriboe90** [comment]
Hi Pedro,
I don't think the warning message is related to your issue. It is raised by the FDSReader. When you open your simulation results in Smokeview, do you see plausible results for the extinction coefficients slice file? Can you maybe upload your simulation results somewhere, so I can try to reproduce the problem with your data?

Best,

Kristian

**Comment by PVR93** [comment]
Hi Kristian,

Thank you for your input! Apparently the results are ok but I don't get why the tool is not working.
![model](https://github.com/user-attachments/assets/4b4f8b9f-5170-434e-8867-0d798518e9e8)

I’ve uploaded my simulation results to wetransfer where it would be available for the next 7days. You can access them using the following link : https://we.tl/t-xaz8JTUIgd

Please let me know if you encounter any issues or need further information.

Regards,

Pedro

**Comment by kriboe90** [comment]
Hi Pedro,

I am sorry I did not manage to download your simulation data in time. However, there was an issue with the FDSReader with newer FDS versions in loading SLC file data that probably led to the error you encountered. I have updated the requirements of the FDSVismap package so that the latest version of the FDSReader will be installed. This should fix your issue. Please let me know if that worked for you.

Best

Kristian
